feat: Create api routes
suspsaude/susp-backend pull request #1
Opened 2024-09-05 00:32 UTC by OJarrisonn

This PR creates the 3 needed API routes, but don't implement them.

2024-09-08 17:53 UTC, Marcoszz requested changes
![image](https://github.com/user-attachments/assets/deb8bdee-e1da-44a0-9162-dad8c9721a52)
Tô tomando _Internal Server Error_ em todas as rotas, pode verificar?

2024-09-08 17:53 UTC, Marcoszz commented on src/app.py
> +@app.get("/detalhes")
Troca o nome dessa rota para `/unidades/detalhes`

2024-09-08 17:53 UTC, Marcoszz commented on src/app.py
>  async def root():
Pode excluir essa rota

2024-09-08 17:57 UTC, Marcoszz commented
Also, vcs precisam que a aplicação rode com Python 3.12? Estou usando o 3.10 aqui. Se sim, eu aconselho fortemente vcs a usarem Docker.

Outra sugestão, só que importante: seria interessante vocês criarem algum `Makefile` ou `.sh` pra fazer todo esse processo de preparação da `.venv` e start da aplicação. Eu segui o tutorial diretinho e tá de boas, mas seria algo legal pra vocês mesmos!

2024-09-08 19:03 UTC, OJarrisonn commented on src/app.py
> +@app.get("/detalhes")
Ok, embora no projeto que tinhamos feito originalmente a rota se chamava apenas `/detalhes`

2024-09-08 19:09 UTC, OJarrisonn commented on src/app.py
>  async def root():
Resolvi manter para ser uma rota para você checar rapidamente se o servidor está rodando

2024-09-09 00:06 UTC, Marcoszz commented on src/app.py
>  async def root():
Tudo bem!

2024-09-09 00:08 UTC, Marcoszz approved these changes

2024-09-09 00:08 UTC, Marcoszz commented on src/app.py
> +- `/detalhes?cnes=`: Retorna detalhes de uma unidade de saúde a partir do numero CNES da unidade.
Trocar o nome da rota de detalhes na descrição

2024-09-15 23:43 UTC, merged