Added DB populator + scripts refactoring
suspsaude/susp-backend pull request #8
Opened 2024-09-23 18:54 UTC by th-duvanel

Hey guys, after some time I finally made to the database populator script. 
Let's check what i've did in the past week, plus the modifications in the current repository configuration:

# Structure

1. Removed `/scripts/data` folder, since we aren't going to have any other script than data ones.
2. Added the `/cache/` folder (in our imagination, cuz Git doesn't let us commit empty folder, so we doesn't have to put its name in gitignore)
3. Added a `/src/db/` folder to separate its configurations

# Scripts

1. Added the database populator script (of course)
2. Removed the class tables from @OJarrisonn csv processor script and moved it to the `/src/db/` folder.
3. Did some modifications on my `fetcher.py` script to attend the new configurations
4. Did some modifications on `process_sus_data.py` script to attend the new populator
5. Finally, added the sqlalchemy requirement.

I didn't test it enough yet because I'm thinking about modifying some code and I would like to ask for opinions on it. I will make another PR about modifying the `Dockerfile` to attend to the new populator script, because we really need to use it inside the container.

2024-09-23 23:17 UTC, OJarrisonn requested changes

2024-09-23 23:17 UTC, OJarrisonn commented on scripts/populator.py
> +DB_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@localhost:5432/{DB_NAME}"
Futuramente, pode ser necessário adicionar uma variável para não usar esse `localhost` hardcoded. Dentro da composição do docker esse script só funcionaria se fosse executado dentro da docker que possui o banco

2024-09-23 23:17 UTC, OJarrisonn commented on scripts/populator.py
> +        populate_db_from_object(GeneralInfo)
`GeneralInfo` já é o nome de uma classe. Como isso é um valor, opte por `general_info`

`PascalCase` para tipos, `snake_case` para variáveis e funções

2024-09-23 23:17 UTC, OJarrisonn commented on scripts/populator.py
> +    for record in ServiceRecords:
Opte por `records` ao invés de `ServiceRecords`

2024-09-23 23:25 UTC, th-duvanel commented on scripts/populator.py
> +DB_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@localhost:5432/{DB_NAME}"
Concordo. Coloquei esse URL apenas para ter alguma coisa para acessá-lo, mas com certeza era bom mudar. Aceito sugestões.

No caso, era uma boa por como ENVvar tbm?

2024-09-23 23:25 UTC, th-duvanel commented on scripts/populator.py
> +        populate_db_from_object(GeneralInfo)
Certo, corrigido.

2024-09-23 23:25 UTC, th-duvanel commented on scripts/populator.py
> +    for record in ServiceRecords:
Ok, já alterado.

2024-09-24 13:10 UTC, OJarrisonn commented on scripts/populator.py
> +DB_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@localhost:5432/{DB_NAME}"
Isso

2024-09-24 13:13 UTC, OJarrisonn commented
Por uma questão de implementação eu gostaria de solicitar uma nova tabela. Essa tabela seria uma lista de strings únicas contendo todas as especialidades. Para povoar essa tabela basta pegar a propriedade `service` de todos `ServiceRecord`, removendo as repetições.

Com isso a rota `/especialidades` será muito mais eficiente

2024-09-24 15:19 UTC, th-duvanel commented
> Por uma questão de implementação eu gostaria de solicitar uma nova tabela. Essa tabela seria uma lista de strings únicas contendo todas as especialidades. Para povoar essa tabela basta pegar a propriedade `service` de todos `ServiceRecord`, removendo as repetições.
> 
> Com isso a rota `/especialidades` será muito mais eficiente

Boa ideia. Posso fazer isso rapidinho.
Inclusive, faltou algo bem importante: filtrar apenas as unidades de SP. Vamos poder remover a coluna de município, e é algo bem fácil de fazer.

Inclusive, vou acr

2024-09-25 13:34 UTC, nahharris commented on scripts/populator.py
> +from src.db.tables import Base, GeneralInfo, ServiceRecord, MedicalService
Esse import está funcionando?

2024-09-25 13:34 UTC, nahharris commented on scripts/populator.py
> +    populate_general_info()
Poderia ser mais interessante que essa variável elasticnes não fosse global, mas sim passada como argumento para as funções que necessitam

2024-09-25 13:34 UTC, OJarrisonn commented on scripts/populator.py
> +    for service in medical_service:
Deveria ser `medical_services`

2024-09-25 14:11 UTC, th-duvanel commented on scripts/populator.py
> +from src.db.tables import Base, GeneralInfo, ServiceRecord, MedicalService
Para funcionar o import é necessário modificar a variável de ambiente `PYTHONPATH` para o diretório do projeto ser tratado como raiz. Ela terá que ser modificada logo após o Docker iniciar. Vou modificar isso no Dockerfile.

2024-09-26 17:41 UTC, th-duvanel commented
Consertei vários problemas e segui as recomendações do @OJarrisonn.

Como tem vários commits, o ideal era fazer um squash deles ao mergear, senão via ficar muito repetitivo, já que eu coloquei um commit por arquivo modificado.

2024-09-26 17:42 UTC, th-duvanel commented on scripts/populator.py
> +from src.db.tables import Base, GeneralInfo, ServiceRecord, MedicalService
Para funcionar, é necessário a PYTHON_PATH estar definida. No docker o ideal é ela já estar definida.

2024-09-26 23:05 UTC, th-duvanel commented
Olá a todos,
Temos um problema: o .csv que imaginávamos que ia ser suficiente, não é. Ao baixar os arquivos de dados "genéricos" como meu script faz, ele baixa um zip com várias informações separadas.

Temos duas opções para seguir: 

1. Baixar na marra o arquivo .csv, o que não necessitaria de modificação no script mas removeria totalmente a "automateza" dele
2. Modificar totalmente as tabelas, uma para cada arquivo, e fazer as rotas se virarem.

Independente da escolha, eu não vou continuar fazendo essas tasks sozinho por terem uma complexidade mais escalável. O certo é seguir a segunda opção, bastaria completar meu script populator com mais tabelas e suas respectivas funções populadoras, além, claro, de selecionar os arquivos necessários.

Atualmente, o PR possui problemas ainda que não têm a ver com os fatos que eu falei acima. Em breve irei dar mais commits que consertam esses problemas, então o problema será apenas lógico agora.

Gostaria de saber a opinião de vocês sobre como vamos seguir e como vamos separar essas tarefas para cada um. Eu até poderia extender essa issue para outra sprint e fazer sozinho, mas imagino que vocês estão dependendo de mim para poder fazer todas as rotas.

Fico no aguardo de vocês para seguir o próximo passo.
@OJarrisonn @jppaulo06

2024-09-29 17:20 UTC, OJarrisonn commented
> Independente da escolha, eu não vou continuar fazendo essas tasks sozinho por terem uma complexidade mais escalável. O certo é seguir a segunda opção, bastaria completar meu script populator com mais tabelas e suas respectivas funções populadoras, além, claro, de selecionar os arquivos necessários.

Sem problema, eu assumo essa no próximo ciclo

2024-10-02 16:50 UTC, OJarrisonn commented
O script já está pronto para uso, mas com algumas ressalvas:

- O `.csv` que vem do elasticnes deve ser baixado manualmente e salvo como `data/DADOS_CNES.csv`
- Alguns downloads do adasus falham em duas formas diferentes: o servidor rejeita a conexão ou o servidor envia uma paǵina de erro. No primeiro caso tentamos o download novamente, no segundo caso ignoramos a unidade
- É necessário executar `drop table` manualmente no banco de dados antes de executar o script

Mudanças sugeridas para uma próxima versão:

- Baixar automaticamente o csv do elasticnes
- Usar um modelo transacional reversível para apagar as tabelas, popular novamente e só então _commitar_  as mudanças concluindo a transação
- Verificar apropriadamente se o download do adasus foi bem sucedido e tentar novamente caso falhe (no segundo caso)
- Apagar código não utilizado

@jppaulo06 gostaria que você tentasse executar esse script e aprovasse esse PR

```
docker compose --profile dev up --build
# entre no container do servidor com docker exec
python3 scripts/populator.py
```

2024-10-03 18:21 UTC, OJarrisonn commented on scripts/populator.py
> +    #populate_medical_services(elasticnes)
Tem de descomentar essa linha @OJarrisonn

2024-10-03 18:21 UTC, OJarrisonn commented on scripts/populator.py
> +    #populate_service_records(elasticnes)
Essa também @OJarrisonn

2024-10-26 20:14 UTC, merged